### ISSUE TITLE
Is this semi-hard coding of the bucket intended here?

### ISSUE THREAD

**Issue by callum-contino** [JamesWoolfenden/terraform-aws-codebuild#6]
https://github.com/JamesWoolfenden/terraform-aws-codebuild/blob/1cea7396c2cd50a6cdd90444a12283dd1ddad26a/data_iam_policy.codebuild_policy.tf#L20

Won't this limit re-use of this module to one user per region?

**Comment by JamesWoolfenden** [comment]
TBH its ages since ive used it myself, I cant imagine I didnt do it on purpose ill check.

**Comment by JamesWoolfenden** [comment]
removing
